version: '3.7'

x-node-env: &node-env
  NODE_ENV: development
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-service: &node-service
  tty: true
  init: true
  image: node:16.12-alpine
  working_dir: /cms-apis
  volumes:
    - .:/cms-apis:cached
    - ./node_modules:/cms-apis/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *node-env

x-env-legacy-mongodb: &legacy-mongodb-env
  LEGACY_MONGO_URL: ${LEGACY_MONGO_URL-mongodb://mongodb-legacy:27017}

services:
  commands:
    <<: *node-service
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  graphql:
    <<: *node-service
    working_dir: /cms-apis/graphql
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *node-env
      <<: *legacy-mongodb-env
      EXPOSED_HOST: cms-apis-graphql.dev.parameter1.com
      EXPOSED_PORT: 11760
      HOST: cms-apis-graphql.dev.parameter1.com
      SHUTDOWN_GRACE_PERIOD: 0
    hostname: cms-apis-graphql.dev.parameter1.com
    ports:
      - "11760:80"
    depends_on:
      - mongodb-legacy

  mongodb-legacy:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb-legacy:/data/db
    ports:
      - "11660:27017"

volumes:
  mongodb-legacy: {}
  yarn-cache: {}
